---
- name: Install DevOps Tools
  hosts: all
  become: yes
  vars:
    terraform_version: "1.5.7"
    terragrunt_version: "v0.52.1"
    atlantis_version: "v0.27.1"
    terragrunt_atlantis_config_version: "1.16.0"
    sonarqube_version: "9.9.1.69595"  # Added for completeness

  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Gather facts
      setup:

    - name: Determine Atlantis URL
      set_fact:
        atlantis_url: "http://{{ ansible_default_ipv4.address }}:4141"

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - jq
        - openjdk-11-jdk
        - wget

    - name: Install AWS CLI
      ansible.builtin.shell: >
        curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o /tmp/awscliv2.zip
        && unzip -o /tmp/awscliv2.zip -d /tmp
        && /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      args:
        executable: /bin/bash

    - name: Install Terraform
      ansible.builtin.shell: >
        curl -fsSL https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_arm64.zip -o /tmp/terraform.zip
        && unzip -o /tmp/terraform.zip -d /usr/local/bin/
      args:
        executable: /bin/bash

    - name: Install Terragrunt
      ansible.builtin.shell: >
        curl -fsSL https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_version }}/terragrunt_linux_arm64 -o /usr/local/bin/terragrunt
        && chmod +x /usr/local/bin/terragrunt
      args:
        executable: /bin/bash

    - name: Install Atlantis
      ansible.builtin.shell: >
        curl -fsSL https://github.com/runatlantis/atlantis/releases/download/{{ atlantis_version }}/atlantis_linux_arm64.zip -o /tmp/atlantis.zip
        && unzip -o /tmp/atlantis.zip -d /usr/local/bin/
        && chmod +x /usr/local/bin/atlantis
      args:
        executable: /bin/bash

    - name: Install terragrunt-atlantis-config
      ansible.builtin.shell: >
        curl -fsSL https://github.com/transcend-io/terragrunt-atlantis-config/releases/download/v{{ terragrunt_atlantis_config_version }}/terragrunt-atlantis-config_{{ terragrunt_atlantis_config_version }}_linux_arm.tar.gz -o terragrunt-atlantis-config.tar.gz
        && tar -xzf terragrunt-atlantis-config.tar.gz -C /tmp/
        && mv /tmp/terragrunt-atlantis-config_{{ terragrunt_atlantis_config_version }}_linux_arm/terragrunt-atlantis-config_{{ terragrunt_atlantis_config_version }}_linux_arm /usr/local/bin/terragrunt-atlantis-config
      args:
        executable: /bin/bash

    - name: Create /etc/atlantis directory
      file:
        path: /etc/atlantis
        state: directory
        mode: 0755

    - name: Copy repos.yaml (Atlantis configuration)
      copy:
        src: ../files/repos.yaml
        dest: /etc/atlantis/repos.yaml
        mode: 0644

    - name: Copy start-atlantis.sh
      copy:
        src: ../files/start-atlantis.sh
        dest: /etc/atlantis/start-atlantis.sh
        mode: 0755

    - name: Copy atlantis.var
      copy:
        src: ../files/atlantis.var
        dest: /etc/atlantis/atlantis.var
        mode: 0644

    - name: Create /var/log/atlantis.log file
      file:
        path: /var/log/atlantis.log
        state: touch
        mode: 0644

    - name: Copy Atlantis service file
      template:
        src: ../files/atlantis.service
        dest: /etc/systemd/system/atlantis.service
        mode: 0644

    - name: Reload systemd and start Atlantis service
      systemd:
        name: atlantis
        state: restarted
        enabled: yes

    # SonarQube installation tasks
    - name: Create sonarqube user
      user:
        name: sonarqube
        system: yes
        shell: /bin/bash

    - name: Create SonarQube directories
      file:
        path: "{{ item }}"
        state: directory
        owner: sonarqube
        group: sonarqube
        mode: '0755'
      with_items:
        - /etc/sonarqube
        - /var/log/sonarqube
        - /var/lib/sonarqube
        - /var/run/sonarqube

    - name: Download SonarQube
      ansible.builtin.shell: >
        curl -fsSL https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip -o /tmp/sonarqube.zip
      args:
        executable: /bin/bash

    - name: Extract SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /etc/sonarqube
        remote_src: yes
        owner: sonarqube
        group: sonarqube
        mode: '0755'

    - name: Create SonarQube service file
      template:
        src: ../files/sonarqube.service
        dest: /etc/systemd/system/sonarqube.service
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start SonarQube service
      systemd:
        name: sonarqube
        state: started
        enabled: yes

